version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "telegram-crypto-bot"
s3_bucket = "oner-sam-bucket"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []