AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.13

  SAM Template for telegram-crypto-bot

Parameters:
  TelegramBotToken:
    Type: String
    Description: >-
      Token of Telegram bot obtained from BotFather
  CoinMarketCapAPIKey:
    Type: String
    Description: >-
      CoinMarketCap API Key to map coin symbols to coin names
  TelegramWebhookSecret:
    Type: String
    Description: >-
      Secret token for webhook validation from Telegram
    Default: ""
  GitHubOrg:
    Type: String
    Description: >-
      GitHub organization or username that owns the repository
    Default: "OnerInce"
  GitHubRepo:
    Type: String
    Description: >-
      GitHub repository name (without org prefix)
    Default: "telegram-crypto_bot"

Globals:
  Function:
    Timeout: 5

Resources:
  CryptoBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.lambda_handler
      Runtime: python3.13
      Environment:
        Variables:
          BOT_TOKEN: !Ref TelegramBotToken
          TELEGRAM_WEBHOOK_SECRET: !Ref TelegramWebhookSecret
          LOG_LEVEL: INFO
      Architectures:
        - arm64
      Events:
        CryptoBot:
          Type: Api
          Properties:
            Path: /getPrice
            Method: post

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-telegram-crypto-bot
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com"
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/master"
      Policies:
        - PolicyName: GitHubActionsDeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CloudFormationAccess
                Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStackResource
                  - cloudformation:GetTemplate
                  - cloudformation:GetTemplateSummary
                  - cloudformation:ValidateTemplate
                  - cloudformation:ListStackResources
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:ListChangeSets
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/telegram-crypto-bot/*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31"
              - Sid: S3ArtifactAccess
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  - arn:aws:s3:::oner-sam-bucket
                  - arn:aws:s3:::oner-sam-bucket/*
              - Sid: LambdaAccess
                Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:DeleteFunction
                  - lambda:GetFunction
                  - lambda:GetFunctionConfiguration
                  - lambda:ListFunctions
                  - lambda:PublishVersion
                  - lambda:AddPermission
                  - lambda:RemovePermission
                  - lambda:GetPolicy
                  - lambda:TagResource
                  - lambda:UntagResource
                  - lambda:ListTags
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:telegram-crypto-bot-*"
              - Sid: APIGatewayAccess
                Effect: Allow
                Action:
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:PATCH
                  - apigateway:DELETE
                  - apigateway:TagResource
                  - apigateway:UntagResource
                Resource:
                  - !Sub "arn:aws:apigateway:${AWS::Region}::/*"
              - Sid: IAMRoleForLambdaAccess
                Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:UpdateRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:PassRole
                Resource:
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/telegram-crypto-bot-*"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/github-actions-telegram-crypto-bot"
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:DescribeLogGroups
                  - logs:PutRetentionPolicy
                  - logs:TagLogGroup
                  - logs:UntagLogGroup
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/telegram-crypto-bot-*"

Outputs:
  CryptoBotApi:
    Description: "API Gateway endpoint URL for Prod stage for CryptoBot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getPrice/"
  CryptoBotFunction:
    Description: "Telegram Crypto Bot Lambda Function"
    Value: !GetAtt CryptoBotFunction.Arn
  CryptoBotFunctionIamRole:
    Description: "Implicit IAM Role created for CryptoBot function"
    Value: !GetAtt CryptoBotFunctionRole.Arn
  GitHubActionsRoleArn:
    Description: "IAM Role ARN for GitHub Actions OIDC — store as AWS_ROLE_ARN GitHub secret"
    Value: !GetAtt GitHubActionsRole.Arn
